### ISSUE TITLE
Can't reproduce LLMs training, missing files

### ISSUE THREAD

**Issue by oserikov** [cmavro/GNN-RAG#12]
Hi! Could you please tell how do I get these files:

https://github.com/cmavro/GNN-RAG/blob/28d31bc0db3d54f0930e6125f1c98b5b1ace1ba4/llm/scripts/train.sh#L2

?

Do I get these files by aligning https://huggingface.co/datasets/rmanluo/RoG-$DATASET files? This would not yield all the files listed...

**Comment by cmavro** [comment]
Training files can be obtained by this repo https://github.com/RManLuo/reasoning-on-graphs
