### ISSUE TITLE
the function of "create_parser_nutrea" is missing

### ISSUE THREAD

**Issue by ZeroerWiser** [cmavro/GNN-RAG#14]
The default hyperparamters setting is missing in the file"parsing.py"

**Comment by kunal-sinha-coding** [comment]
Yep just got this as well when I tried to run the suggested command in the gnn section's readme. Looking into it. Could we just comment it out for now? Doesn't seem to be being used

**Comment by cmavro** [comment]
This is TBD; we will look into adding more GNNs in the future.
