### ISSUE TITLE
Problem with Precision Computation

### ISSUE THREAD

**Issue by iamshahd** [cmavro/GNN-RAG#15]
Hi,
I am facing a problem with the precision values. Although I was able to reproduce the recall, there seems to be a problem with the precision computation. In the below example, although the answer is correct, the precision is computed to be 0.077. To me this looks like the LLM sequence isn't being parsed correctly, perhaps taking all of the generated sequence as the set of answers, which would result in recall=1.0 and low precision. I wonder if the results reported in the paper have been computed based on a different logic. Appreciate your help. Thanks.

![image](https://github.com/user-attachments/assets/aa673c48-e902-4d2d-a7ac-899cc4bd0a7e)

**Comment by cmavro** [comment]
Thanks for the question. Could you provide more information on the command you run and particularly which LLM you use?

If the LLM is not tuned to generate a list of answers, as RoG is, then precision/F1 metrics become uncontrollable. In the paper, we report F1 metric for the tuned LLaMa model (RoG) and Hit for other untuned  LLMs.

**Comment by iamshahd** [comment]
Thanks for your reply!

I ran the `plug-and-play.sh` script with the below params which are using `llama2-chat-hf`. If we are using any of the untuned LLMs, should we look at the hits only (discarding all other metrics)? Have you experimented with prompt engineering to ensure the untuned LLMs generate a list of answers in standardized format?

```
SPLIT="test"
DATASET_LIST="RoG-cwq"
BEAM_LIST="3"
MODEL_LIST="llama2-chat-hf"
PROMPT_LIST="prompts/llama2_predict.txt"
```

**Comment by cmavro** [comment]
Yes, focus on Hit for untuned LLMs. We did not perform prompt engineering, but feel free to experiment with.

**Comment by iamshahd** [comment]
Will do, thank you!
