### ISSUE TITLE
Evaluation of the Pre-trained GNN Retriever on CWQ

### ISSUE THREAD

**Issue by mufeili** [cmavro/GNN-RAG#17]
The [README file](https://github.com/cmavro/GNN-RAG/tree/main/gnn) only provides the instructions for evaluating the pre-trained retriever for WebQSP, but not for CWQ. I tried to perform reverse engineering, leading to

```bash
python main.py ReaRev --num_epoch 200 --batch_size 8 --eval_every 2 --data_folder data/CWQ/ --lm sbert --num_iter 3 --num_ins 3 --num_gnn 3 --relation_word_emb True --load_experiment ReaRev_CWQ.ckpt --is_eval --name cwq --entity_dim 50
```

but the results I got were quite low
```bash
evaluation.......
how many eval samples...... 3519
avg_em 0.48366013071895425
avg_hits 0.2929809605001421
avg_f1 0.2595035526392219
avg_precision 0.23844268935116564
avg_recall 0.4462387509888053
{3: 3509, 2: 10}

2024-11-14 23:57:48,086 - root - INFO - EVAL F1: 0.2595, H1: 0.2930, EM 0.4837
evaluation.......
how many eval samples...... 3531
avg_em 0.4525630133106769
avg_hits 0.2832058906825262
avg_f1 0.24900376706336044
avg_precision 0.23156428560114645
avg_recall 0.4196681669667982
{3: 3519, 2: 12}
```
Are these correct? If not, could you share the instructions you used? Thanks.

**Comment by cmavro** [comment]
It looks like your command is incorrect. Please use `--num_iter 2` (see [here](https://github.com/cmavro/GNN-RAG/blob/main/gnn/scripts/rearev_cwq.sh)).

**Comment by mufeili** [comment]
Thank you so much for the prompt response! The new result looks better.

```bash
avg_em 0.6864910790144435
avg_hits 0.5287453979042764
avg_f1 0.4781533370330245
avg_precision 0.4558152167404276
avg_recall 0.6569451293034718
{3: 3524, 2: 7}
```

I'll close the issue unless this is still unexpected.
