### ISSUE TITLE
What are the difference between the data folders provided in Google drive?

### ISSUE THREAD

**Issue by leekum2018** [cmavro/GNN-RAG#5]
What are the difference between cwq and sr-swq, or webqsp and sr-webqsp?
<img width="364" alt="Screenshot 2024-06-27 at 15 39 51" src="https://github.com/cmavro/GNN-RAG/assets/48008881/7dcc2c72-b13c-4fa5-a981-16d4240ea823">

**Comment by cmavro** [comment]
Hi, thanks for your interest in our work!

"SR" versions of the datasets include the KG subgraphs as retrieved by the [SR](https://github.com/RUCKBReasoning/SubgraphRetrievalKBQA) method. We have an ablation study in Table 15 of Appendix D. You do not need these datasets for the main results.

**Comment by leekum2018** [comment]
> Hi, thanks for your interest in our work!
> 
> "SR" versions of the datasets include the KG subgraphs as retrieved by the [SR](https://github.com/RUCKBReasoning/SubgraphRetrievalKBQA) method. We have an ablation study in Table 15 of Appendix D. You do not need these datasets for the main results.

Thanks for your reply. Does it mean the subgraphs in the non-"sr" datasets are retrieved by  [NSM](https://github.com/RichardHGL/WSDM2021_NSM)?

**Comment by cmavro** [comment]
Yes, correct!

**Comment by leekum2018** [comment]
Thanks. One more question. What is the purpose of the argument `add_rule` in `predict_answer.py`?

**Comment by cmavro** [comment]
Argument `add_rule` adds the paths retrieved by RoG LLM (GNN-RAG + RA) [here](https://github.com/cmavro/GNN-RAG/blob/28d31bc0db3d54f0930e6125f1c98b5b1ace1ba4/llm/src/qa_prediction/build_qa_input.py#L93).

**Comment by leekum2018** [comment]
Sorry, I have another question. Notice that some paths for input contains entities that have not been decoded, i.e., represented by their Freebase ID, instead of their name. I would like to know whether all of such entities are CVT nodes? Are there any possibilities that some entities that are not CVT node still shows their ID due to some reasons?
