### ISSUE TITLE
Why we are using the test.json when we storing the result from gnn as test .info

### ISSUE THREAD

**Issue by Lavishgurjar85** [cmavro/GNN-RAG#6]
def load_gnn_rag(g_data_file, g_data_file2=None):
    data_file_d = {}
    data_file_gnn = {}

    data_file = os.path.dirname(g_data_file) + "/test.json"
    with open(data_file) as f_in, open(g_data_file) as fg:
        for line, lineg in (zip(f_in, fg)):
            line = json.loads(line)
            lineg = json.loads(lineg)
            
            data_file_d[line["id"]] = line
            data_file_gnn[line["id"]] = lineg
        print("ok1")
    if g_data_file2 is not None:
        data_file = os.path.dirname(g_data_file2) + "/test.json"
        with open(data_file) as f_in, open(g_data_file2) as fg:
            for line, lineg in (zip(f_in, fg)):
                line = json.loads(line)
                lineg = json.loads(lineg)
                
                cand1 = data_file_gnn[line["id"]]["cand"]
                cand2 =  lineg["cand"]

                for c2 in cand2: #c[0] entity c[1] score
                    found=False
                    for c1 in cand1:
                        if c2[0] == c1[0]:
                            if c2[1] > c1[1]: c1[1] = c2[1]
                            found=True
                            break
                    if not found:
                        cand1.append(c2)
                cand1 = sorted(cand1, key=lambda x: x[1], reverse=True)
                data_file_gnn[line["id"]]["cand"] = cand1
            data_file_gnn[line["id"]].update({"cand2": lineg["cand"]})
            print("ok2")

    return data_file_gnn

In this why we used test.json instead of test.info
Also if we use test.info it does'nt contains ids

**Comment by cmavro** [comment]
You need to ~~rename~~ move `test.info` **and** `test.json` (from the gnn data folder) to the corresponding folder (see [here](https://github.com/cmavro/GNN-RAG/blob/28d31bc0db3d54f0930e6125f1c98b5b1ace1ba4/gnn/README.md?plain=1#L22)).

We will add new automatic scripts at the near future.

**Comment by Lavishgurjar85** [comment]
The thing is there are two files we are using
data_file = "/test.json"
g_data_file = "/test.info"

if I only use test.info by renaming it too test.json
The problem occurs is 
 cand1 = data_file_gnn[line["id"]]["cand"]
 we require "id" for this but in test.info the data is
 {"question": "lou seal is the mascot for the team that last won the world series when ? ", "0": {}, "1": {}, "answers": ["m.0117q3yz"], "precison": 0.3333333333333333, "recall": 1.0, "f1": 0.5, "hit": 1.0, "cand": [["m.0117q3yz", 0.34248173236846924], ["m.09gnk2r", 0.328049898147583], ["m.0ds8qct", 0.32790225744247437]]}
 there is no "id"

**Comment by cmavro** [comment]
Correct, I updated the previous message. You need both `test.info` and `test.json` from the gnn data to the new folder:
<img width="183" alt="image" src="https://github.com/cmavro/GNN-RAG/assets/43810712/0ac209e4-90be-4256-ba8c-ecd17eb300fe">

**Comment by Lavishgurjar85** [comment]
Can you please specify where this test.json files are 
Actually in the repository only test.info files are present

**Comment by Liuuulu** [comment]
Error after file renaming：Traceback (most recent call last):
  File "/home/zhang/GNN-RAG/llm/src/qa_prediction/predict_answer.py", line 338, in <module>
    main(args, LLM)
  File "/home/zhang/GNN-RAG/llm/src/qa_prediction/predict_answer.py", line 192, in main
    data_file_gnn = load_gnn_rag(args.rule_path_g1)
  File "/home/zhang/GNN-RAG/llm/src/qa_prediction/predict_answer.py", line 54, in load_gnn_rag
    data_file_d[line["id"]] = line
KeyError: 'id'

**Comment by kunal-sinha-coding** [comment]
I am getting the same issue! The test.info files do not have ids but we need ids for the rag-reasoning.sh script to run.

**Comment by small-code-cat** [comment]
@cmavro I also encountered the problem of missing test.json. When running rag-reasoning.sh, I used the test.info you provided, but there was no test.json in the same directory. Looking forward to your reply.

**Comment by cmavro** [comment]
`test.json` files are large to be uploaded in Github. These files are the same with previous works ReaRev, NSM, etc. -- I also re-upload them here: https://drive.google.com/drive/folders/1-wCf3DGj5xVAWkHScBrZQ3Xpy9M5WcC3?usp=sharing

**Comment by small-code-cat** [comment]
> `test.json` files are large to be uploaded in Github. These files are the same with previous works ReaRev, NSM, etc. -- I also re-upload them here: https://drive.google.com/drive/folders/1-wCf3DGj5xVAWkHScBrZQ3Xpy9M5WcC3?usp=sharing

Thank you very much!

**Comment by kunal-sinha-coding** [comment]
> `test.json` files are large to be uploaded in Github. These files are the same with previous works ReaRev, NSM, etc. -- I also re-upload them here: https://drive.google.com/drive/folders/1-wCf3DGj5xVAWkHScBrZQ3Xpy9M5WcC3?usp=sharing

Thank you for the response!! I appreciate it
